### ISSUE TITLE
Allow choosing a specific version of base

### ISSUE THREAD

**Issue by lortabac** [Franciman/vabal#1]
It would be useful to have an option to select a specific version of base, and let `vabal` find a compatible GHC version. Of course, `vabal` should not accept a base version that is outside the bounds set in the `.cabal` file.

**Comment by Franciman** [comment]
Seems reasonable. Suppose we call this option `--with-base-version`.
If a user specifies both `--with-ghc-version` and `--with-base-version`, what do you think would be a sane behavior? Ignore the base-version constraint?

**Comment by lortabac** [comment]
Maybe it is better to be explicit and disallow using both options at the same time.

**Comment by Franciman** [comment]
Option added with 25e517805ff706e39b5b13d035347ceb83cc0697, thank you!
