### ISSUE TITLE
test:test-on-hackage requires a network connection

### ISSUE THREAD

**Issue by fgaz** [Franciman/vabal#15]
This will make the test fail in some isolated build environments (like nix)

**Comment by Franciman** [comment]
metadata needed by `vabal` is downloaded. This metadata is needed for `vabal` usage. Is this an issue, too?

Also how do you think I should fix the test? By manually inserting the metadata in the test?

**Comment by fgaz** [comment]
> metadata needed by `vabal` is downloaded. This metadata is needed for `vabal` usage. Is this an issue, too?

You mean the metadata downloaded at runtime by `cabal update`, right? That's not an issue, only build-time downloads are

> Also how do you think I should fix the test? By manually inserting the metadata in the test?

That's a possible solution, but since the hackage index is _big_ including it in the package is not ideal :-/

Maybe just a subset of the index?

**Comment by Franciman** [comment]
Oh, it's not the hackage package set, it's this: https://github.com/Franciman/vabal-ghc-metadata/blob/master/vabal-ghc-metadata.csv

The hackage package set is not downloaded (if it's not there, the test just fails)

**Comment by Franciman** [comment]
Fixed by c00ca9db2ce9c5af9f0e5653a78de70508c410e8
