### ISSUE TITLE
[RFC] Multiple projects support

### ISSUE THREAD

**Issue by Franciman** [Franciman/vabal#17]
This issue is related to #11 in that they both are related to the `cabal.project` file.
What do you think should be the behavior of `vabal` in presence of a `cabal.project` that indicates multiple projects?

Some ideas that come to my mind now are:
- Make vabal analyze the cabal file of each package and determine one `ghc` version that works for all (if any, this is the tricky part: there may not be any ghc version that is fine for all packages, but different versions for each package could)
- Make vabal determine a `ghc` version for each package: How would this information be used by the user? Right now cabal doesn't seem to support different ghcs for multiple packages.

/CC @lortabac @fgaz @jabberabbe

**Comment by fgaz** [comment]
Doesn't cabal-install solve for all packages in the project? Then the first one is the only possible option

**Comment by fgaz** [comment]
https://cabal.readthedocs.io/en/latest/nix-local-build.html#cfg-field-with-compiler

> At the moment, it’s not possible to set with-compiler on a per-package basis, but eventually we plan on relaxing this restriction. If this is something you need, give us a shout.

**Comment by jabberabbe** [comment]
I agree with @fgaz, today the only possible solution is to determine a single version, shared by all packages. Then vabal should take a `—project-file` option to specify the name of the project file and of the local configuration file which is generated by `vabal configure` (by adding the suffix `.local`).
I think that vabal should output a warning if a GHC version is already specified in the project file, to make easier to use `vabal | xargs -r cabal ...` as a drop-in replacement for `cabal`.

**Comment by lortabac** [comment]
Any news on this one?

**Comment by Franciman** [comment]
I haven't had the chance to work on it yet. But it's the next thing on the list. I'm starting to work on it soon.
I'm looking for a lib to parse the `cabal.project` format, do you know any that would do the job?
