### ISSUE TITLE
Prefer already installed GHC

### ISSUE THREAD

**Issue by Franciman** [Franciman/vabal#5]
When deciding which GHC to use, it could be useful to always prefer already installed `ghc`s over ones that need to be downloaded.
Should this be the default behavior (one could opt out with a flag called `--always-newest`) ?

**Comment by lortabac** [comment]
Yes, definitely! Preferring the GHC binaries that are already installed should be the default option IMHO. It would be annoying if for example `vabal` downloaded and installed a binary each time a new version of GHC is released.
